### ISSUE TITLE
How do I add html in my columns

### ISSUE THREAD

**Issue by creativemind1** [qidaizhe11/element-table-wrapper#1]
Hello,

`<el-table-wrapper :data="topAirlinesData" :columns="columns" style="width:100%;"></el-table-wrapper>`
const topAirlinesData = [] //comes dynamically
const columns = [{prop: 'code', label: 'Code', width: 80}] //

How do I give custom html like link <a href="#">edit</a> in of my columns?

**Comment by qidaizhe11** [comment]
use scopedSlot attr, example: [{prop: 'code', label: 'Code', width: 80, scopedSlot: 'code-slot'}], did not have english document yet, sorry. 

fully example here: https://github.com/qidaizhe11/element-table-wrapper/blob/master/examples/play/Play.vue, may it help.

**Comment by creativemind1** [comment]
actually I wanted to give custom HTML in my data which comes dynamically. I think your solution works.. Thanks
